import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Logo from '../components/Logo'
import NavBar from '../components/NavBar'
import Header from '../containers/Header'
import Hero from '../containers/Hero'
import Services from '../containers/Services'
import Experience from '../containers/Experience'
import Employees from '../containers/Employees'
import Prices from '../containers/Prices'
import Contact from '../containers/Contact'
import Footer from '../containers/Footer'
import DevelopBy from '../components/commons/DevelopBy'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;500;600;700;900&display=swap" rel="stylesheet"/>
        <meta property="og:title" content="Pet Care App" />
        <meta property="og:description" content="A WebSite of pets" />
        <meta property="og:image" content="/PetCareLanding.png" />
      </Head>
      <Header>
        <Logo/>
        <NavBar/>
      </Header>
      <Hero/>
      <Services/>
      <Experience/>
      <Employees/>
      <Prices/>
      <Contact/>
      <Footer/>
      <DevelopBy/>
    </div>
  )
}
